%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Format Goniometer time strings to right format
dates           =   datestr(datevec(Data.ThermoTracer.Date));
[Combined_Data.GTT_date_year    ,...
 Combined_Data.GTT_date_month   ,...
 Combined_Data.GTT_date_day     ,...
 hours                          ,... 
 minutes                        ,...
 seconds                       ]=   datevec(dates);
dates_num                       =   datenum(dates);
times_num                       =   Data.ThermoTracer.Time';
times                           =   datestr(times_num,'HH:MM:SS');
[year                           ,...
 month                          ,...
 day                            ,...
 Combined_Data.GTT_time_hours   ,... 
 Combined_Data.GTT_time_minutes ,...
 Combined_Data.GTT_time_seconds]=   datevec(datestr(times_num,'HH:MM:SS'));
Combined_Data.GTT_time_total_num=   dates_num + times_num;
Combined_Data.GTT_time_total    =   datestr(Combined_Data.GTT_time_total_num);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Format M23 logger time strings to right format
home                            = cd;
cd('d:/data/sun2Flex/data Output/logger/')
M23                             =   load('MR23X_total2.mat')
cd(home)
datenum_day                     =   M23.Values.Minutes.Time_Day_Nums;
temp                            =   datestr(datenum_day + 1,'dd mm');                       %datestr(0) = 00 jan 0000

Combined_Data.M23_date_month    =   str2num(temp(:,4:5));
Combined_Data.M23_date_day      =   str2num(temp(:,1:2));
Combined_Data.M23_time_hours    =   floor(M23.Values.Minutes.Time_Nums/100);
Combined_Data.M23_date_year     =   2005*ones(size(Combined_Data.M23_time_hours));
Combined_Data.M23_time_minutes  =   M23.Values.Minutes.Time_Nums-Combined_Data.M23_time_hours*100;
Combined_Data.M23_time_seconds  =   zeros(size(Combined_Data.M23_time_hours));
Combined_Data.M23_time_total    =   datestr([Combined_Data.M23_date_year                                     ,...
                                             Combined_Data.M23_date_month                                    ,...
                                             Combined_Data.M23_date_day                                      ,...
                                             Combined_Data.M23_time_hours                               ,...
                                             Combined_Data.M23_time_minutes                             ,...
                                             Combined_Data.M23_time_seconds]);
Combined_Data.M23_time_total_num=   datenum(Combined_Data.M23_time_total);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Format C23 logger time strings to right format
home                            = cd;
C23                             =   load('C23X_total.mat')
cd('d:/data/sun2Flex/data Output/logger/')
cd(home)
datenum_day                     =   C23.Values.Minutes.Time_Day_Nums;
temp                            =   datestr(datenum_day + 1,'dd mm');                       %datestr(0) = 00 jan 0000

Combined_Data.C23_date_month    =   str2num(temp(:,4:5));
Combined_Data.C23_date_day      =   str2num(temp(:,1:2));

Combined_Data.C23_time_hours    =   floor(C23.Values.Minutes.Time_Nums/100);
Combined_Data.C23_date_year     =   2005*ones(size(Combined_Data.C23_time_hours));
Combined_Data.C23_time_minutes  =   C23.Values.Minutes.Time_Nums-Combined_Data.C23_time_hours*100;
Combined_Data.C23_time_seconds  =   zeros(size(Combined_Data.C23_time_hours));
Combined_Data.C23_time_total    =   datestr([Combined_Data.C23_date_year                                        ,...
                                             Combined_Data.C23_date_month                                       ,...
                                             Combined_Data.C23_date_date_day                                    ,...
                                             Combined_Data.C23_time_hours                                       ,...
                                             Combined_Data.C23_time_minutes                                     ,...
                                             Combined_Data.C23_time_seconds]);
Combined_Data.C23_time_total_num=   datenum(Combined_Data.C23_time_total);

temp_air                =   C23X.Values.Minutes.Temperature_low;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Compare time strings of Goniometer, M23 logger and C23 logger
maxj                            =   size(Combined_Data.GTT_time_total,1);
Combined_Data.M23_Index(:,1)    =   Combined_Data.M23_time_total_num >= Combined_Data.GTT_time_total_num(1,:)-1e-3 &...
                                    Combined_Data.M23_time_total_num <  Combined_Data.GTT_time_total_num(1,:);
Combined_Data.C23_Index(:,1)    =   Combined_Data.C23_time_total_num >= Combined_Data.GTT_time_total_num(1,:)-1e-3 &...
                                    Combined_Data.C23_time_total_num <  Combined_Data.GTT_time_total_num(1,:);
for j=2:maxj
    Combined_Data.M23_Index(:,j)=   Combined_Data.M23_time_total_num >= Combined_Data.GTT_time_total_num(j-1,:)    &...
                                    Combined_Data.M23_time_total_num <  Combined_Data.GTT_time_total_num(j,:);
    Combined_Data.C23_Index(:,j)=   Combined_Data.C23_time_total_num >= Combined_Data.GTT_time_total_num(j-1,:)    &...
                                    Combined_Data.C23_time_total_num <  Combined_Data.GTT_time_total_num(j,:);                                
end
Combined_Data.M23_Index2        =   Combined_Data.M23_time_total_num >= Combined_Data.GTT_time_total_num(1,:)      &...
                                    Combined_Data.M23_time_total_num <  Combined_Data.GTT_time_total_num(end,:);
Combined_Data.C23_Index2        =   Combined_Data.C23_time_total_num >= Combined_Data.GTT_time_total_num(1,:)      &...
                                    Combined_Data.C23_time_total_num <  Combined_Data.GTT_time_total_num(end,:);                                
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
names                           =  ['Temperature.soil_shade_low_old'    ;   'Temperature.soil_sunny_low_old'    ;...
                                    'Temperature.soil_shade_low_new'    ;   'Temperature.soil_sunny_low_new'    ;...
                                    'Temperature.leaf_shade_low_old'    ;   'Temperature.leaf_shade_low_new'    ;...
                                    'Temperature.leaf_shade_hig_old'    ;   'Temperature.leaf_shade_hig_new'    ;...
                                    'Temperature.leaf_sunny_low_old'    ;   'Temperature.leaf_sunny_low_new'    ;...
                                    'Temperature.leaf_sunny_hig_old'    ;   'Temperature.leaf_sunny_hig_new'];
                                
class_values                    =   [max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),09))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),11))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),10))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),12))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),06))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),08))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),03))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),02))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),05))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),07))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),04))                                ,...
                                     max(M23.Values.Minutes.NTC(find(Combined_Data.M23_Index2),01))];
[l,b]                           =   sort(l);



% %%%%%%%%%Correcting datums strings
% temp1.date      =   datestr(datevec(Data.ThermoTracer.Date));
% temp1.date_num  =   datenum(temp1.date);
% temp1.time_num  =   Data.ThermoTracer.Time';
% temp1.time      =   datestr(temp1.time_num,'HH:MM:SS');
% temp1.total_num =   temp1.date_num + temp1.time_num;
% temp1.total     =   datestr(temp1.total_num);
% 
% Data.ThermoTracer.Raw(Data.ThermoTracer.Raw<0)  =   0;
% 
% CLASSES     =   [0 25 28 30 32 35 38 40 50];
% classes     =   zeros(size(Data.ThermoTracer.Raw,1),...
%                       size(Data.ThermoTracer.Raw,2),...
%                       size(l,2));                  
% maxj        =   size(l,2);
% minj        =   1;
% classes(:,:,1   )   =   Data.ThermoTracer.Raw(:,:,2)<l(1   );
% classes(:,:,maxj)   =   Data.ThermoTracer.Raw(:,:,2)<l(maxj);
% for j=(minj+1):(maxj-1)
%     classes(:,:,j)   =   Data.ThermoTracer.Raw(:,:,2)<l(j) & Data.ThermoTracer.Raw(:,:,2)>=l(j-1);
% end
% 
% for j=2:maxj-1
%     hold on
%     surf(classes(:,:,j)*j,'LineStyle','none')
%     pause(0.1)
% end